=== Javajava1/XML-DTD/person.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!ELEMENT library (Book, Member)>
<!ELEMENT Book (BookId,Title*,Author*,Price*,Publisher*,Cost*)>
<!ELEMENT Member (Name,Address)>
<!ELEMENT Name (FirstName,MiddleName,LastName)>
<!ELEMENT Address (HouseNumber,Street,City)>
<!ELEMENT BookId (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Publisher (#PCDATA)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT MiddleName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT HouseNumber (#PCDATA)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Cost (#PCDATA)>

=== Javajava1/XML-DTD/person.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE library SYSTEM "C:/Users/zhao/Desktop/person.dtd">
<library>
    <Book><BookId>12345</BookId></Book>
    <Member>
		<Name>
			<FirstName>
				li
			</FirstName>
			<MiddleName>
				wu
			</MiddleName>
			<LastName>
				bai
			</LastName>
		</Name>
		<Address>
			<HouseNumber>
				531
			</HouseNumber>
			<Street>
				hanke
			</Street>
			<City>
				jingzhou
			</City>
		</Address>
	</Member>
</library>
